GET http://localhost:8000/api/tickets HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9ubmUiLCJpZCI6IjY2ZjQ2NmExNzkxM2UzN2NiZmVlYWYyNiIsImlhdCI6MTcyNzI5MzE1Nn0.e379sDK7d6_-dmD3ykuHTOin_X8SjGvJgCDHBxPvXPY
###

GET http://localhost:8000/api/ticket HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9ubmUiLCJpZCI6IjY2ZjQ2NmExNzkxM2UzN2NiZmVlYWYyNiIsImlhdCI6MTcyNzI5MzE1Nn0.e379sDK7d6_-dmD3ykuHTOin_X8SjGvJgCDHBxPvXPY
id: 3
###

POST http://localhost:8000/api/ticket HTTP/1.1
Content-Type : application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9ubmUiLCJpZCI6IjY2ZjQ2NmExNzkxM2UzN2NiZmVlYWYyNiIsImlhdCI6MTcyNzI5MzE1Nn0.e379sDK7d6_-dmD3ykuHTOin_X8SjGvJgCDHBxPvXPY

{
  "trip_id": 2,
  "entries": [
    {
      "class": 1,
      "name": "ajdb",
      "seat": "fdsj"
    },
    {
      "class": 2,
      "name": "ajdb",
      "seat": "fdsj"
    },
    {
      "class": 3,
      "name": "ajdb",
      "seat": "fdsj"
    }
  ]
}
###