GET http://localhost:8000/api/users HTTP/1.1
###

GET http://localhost:8000/api/users/66f04abe2c961619aab65cd1 HTTP/1.1
###

POST http://localhost:8000/api/signup HTTP/1.1
Content-Type : application/json

{
  "name": "fjsdkkf",
  "phone": "12345678",
  "email": "chdbwjw@email.com",
  "password": "jcdbwkjlb3874"
}
###

POST http://localhost:8000/api/signin HTTP/1.1
Content-Type : application/json

{
  "email": "chdbwjw@email.com",
  "password": "jcdbwkjlb3874"
}
